export const SEARCH_POSTS = 'SEARCH_POSTS'
export const GET_POSTS = 'GET_POSTS'
export const ADD_POST = 'ADD_POST'
export const REMOVE_POST = 'REMOVE_POSTS'
export const SET_LOADING = 'SET_LOADING'
export const POSTS_ERROR = 'POSTS_ERROR'
